server:
  port: 8090
spring:
  data:
    mongodb:
      username: root
      password: root
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: customer
      authentication-database: admin